// src/pages/data-parser/InputBox.tsx
interface InputBoxProps {
  inputText: string;
  onInputTextChanged: (value: string) => void;
}

export default function InputBox({ inputText, onInputTextChanged }: InputBoxProps) {
  return (
    <div className="container-fluid">
      <div className="row p-0">
        <div className="col-md-12 p-0">
          <div className="card border-dark">
            <div className="card-header text-white">Input Text</div>
            <div className="card-body">
              <div className="form-group">
                <div className="row p-0">
                  <div className="col-md-12 p-0">
                    <textarea
                      className="form-control"
                      id="input-textarea"
                      name="textarea"
                      rows={12}
                      value={inputText}
                      onChange={(e) => onInputTextChanged(e.target.value)}
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// src/app/pages/data-parser/input-box/input-box.component.ts
import { Component, EventEmitter, OnInit, Output } from '@angular/core';

@Component({
  selector: 'app-input-box',
  templateUrl: './input-box.component.html',
  styleUrls: ['./input-box.component.css']
})
export class InputBoxComponent implements OnInit {

  inputText: string = "";
  @Output() onInputTextChanged: EventEmitter<string> = new EventEmitter<string>();

  constructor() { }

  ngOnInit(): void {
  }

  onChange() {
    this.onInputTextChanged.emit(this.inputText);
  }
}

<div class="container-fluid">
  <div class="row p-0">
    <div class="col-md-12 p-0">
      <div class="card border-dark">
        <div class="card-header text-white">Input Text</div>
        <div class="card-body">
          <div class="form-group">
            <div class="row p-0">
              <div class="col-md-12 p-0">
                <textarea class="form-control" id="textarea" name="textarea" rows="12" [(ngModel)]="inputText" (change)='onChange()'></textarea>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
