// src/pages/string-encoder/StringEncoder.tsx
import { useRef, useState } from 'react';

import { copyToClipboard, download, readUploadedFile } from '../../lib/browser-io';
import { Base32Encoder } from './encoders/base32-encoder';
import { Base64Encoder } from './encoders/base64-encoder';
import { HtmlEncoder } from './encoders/html-encoder';
import { LineSorter } from './encoders/line-sorter';
import { SHA512Encoder } from './encoders/sha512-encoder';
import { UrlEncoder } from './encoders/url-encoder';

function transform(currentAlg: string, input: string): string {
  switch (currentAlg) {
    case 'HTML Encode':
      return new HtmlEncoder().encode(input);
    case 'HTML Decode':
      return new HtmlEncoder().decode(input);
    case 'Base32 Encode':
      return new Base32Encoder().encode(input);
    case 'Base32 Decode':
      return new Base32Encoder().decode(input);
    case 'Base64 Encode':
      return new Base64Encoder().encode(input);
    case 'Base64 Decode':
      return new Base64Encoder().decode(input);
    case 'URL Encode':
      return new UrlEncoder().encode(input);
    case 'URL Decode':
      return new UrlEncoder().decode(input);
    case 'Sort Lines':
      return new LineSorter().sort(input);
    case 'SHA512 Hash':
      return new SHA512Encoder().encode(input);
    default:
      return 'Unknown or unsuported selection: ' + currentAlg;
  }
}

export default function StringEncoder() {
  const [input, setInput] = useState('');
  const [currentAlg, setCurrentAlg] = useState('Sort Lines');
  const selectFile = useRef<HTMLInputElement>(null);

  const output = transform(currentAlg, input);

  return (
    <>
      <div className="container">
        <div className="row">
          <div className="col">
            <h3>String Encode/Decode</h3>
          </div>
        </div>
        <div className="row">
          <div className="col">
            <label>Action</label>
          </div>
        </div>
        <div className="row">
          <div className="col">
            <select
              className="form-select"
              value={currentAlg}
              onChange={(e) => setCurrentAlg(e.target.value)}
            >
              {/* Hash options are still to be implemented:
                  SHA-1, SHA-2, SHA224, SHA256, SHA384, SHA512, SHA512/224,
                  SHA512/256, SHA3-224, SHA3-256, SHA3-384, SHA3-512, CRC-16,
                  CRC-32 */}

              <optgroup label="HTML">
                <option>HTML Encode</option>
                <option>HTML Decode</option>
              </optgroup>

              {/* Base32 is not implemented yet:
                  <optgroup label="Base32">
                    <option>Base32 Encode</option>
                    <option>Base32 Decode</option>
                  </optgroup> */}

              <optgroup label="Base64">
                <option>Base64 Encode</option>
                <option>Base64 Decode</option>
              </optgroup>

              <optgroup label="URL">
                <option>URL Encode</option>
                <option>URL Decode</option>
              </optgroup>

              <optgroup label="Other">
                <option>Sort Lines</option>
              </optgroup>
            </select>
          </div>
        </div>
        <div className="row">
          <div className="col">
            <label>Input String</label>
          </div>
        </div>
        <div className="row">
          <div className="col">
            <textarea
              className="form-control"
              rows={10}
              value={input}
              onChange={(e) => setInput(e.target.value)}
            />
          </div>
        </div>
        <div className="row">
          <div className="col"></div>
          <div className="col-auto text-right">
            <button
              className="btn btn-success ms-1 mt-1"
              type="button"
              onClick={() => selectFile.current?.click()}
            >
              Load File
            </button>
            <button className="btn btn-success ms-1 mt-1" type="button" onClick={() => setInput('')}>
              Clear
            </button>
          </div>
        </div>
        <div className="row">
          <div className="col">
            <label>Output Code</label>
          </div>
        </div>
        <div className="row">
          <div className="col">
            <textarea className="form-control" rows={10} readOnly value={output} />
          </div>
        </div>
        <div className="row">
          <div className="col">
            <button className="btn btn-success me-1 mt-1" onClick={() => download('file.txt', output)}>
              Save File
            </button>
          </div>
          <div className="col-auto text-right">
            <button
              className="btn btn-success ms-1 mt-1 float-right"
              type="button"
              onClick={() => copyToClipboard(output, 'Output copied to clipboard')}
            >
              Copy
            </button>
          </div>
        </div>
      </div>

      <input
        style={{ display: 'none' }}
        type="file"
        ref={selectFile}
        onChange={(e) => readUploadedFile(e, setInput)}
      />
    </>
  );
}

// src/app/pages/string-encoder/string-encoder.component.ts
import { Component, OnInit } from '@angular/core';
import { HtmlEncoder } from './encoders/html-encoder';
import { Base32Encoder } from './encoders/base32-encoder';
import { Base64Encoder } from './encoders/base64-encoder';
import { UrlEncoder } from './encoders/url-encoder';
import { LineSorter } from './encoders/line-sorter';
import { SHA512Encoder } from './encoders/sha512-encoder';

@Component({
  selector: 'app-string-encoder',
  templateUrl: './string-encoder.component.html',
  styleUrls: ['./string-encoder.component.css']
})
export class StringEncoderComponent implements OnInit {

  input: string = "";
  currentAlg: string = "Sort Lines";

  constructor() { }

  ngOnInit(): void {
  }

  onClear() {
    this.input = "";
  }

  onSave() {
    this.download("file.txt", this.output);
  }

  onCopy() {
    const el = document.createElement('textarea');
    el.value = this.output;
    el.setAttribute('readonly', '');
    el.style.position = 'absolute';
    el.style.left = '-9999px';
    document.body.appendChild(el);
    el.select();
    document.execCommand('copy');
    document.body.removeChild(el);

    alert("Output copied to clipboard");
  }

  download(filename: string, text: string) {
    let element = document.createElement('a');
    element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(text));
    element.setAttribute('download', filename);

    element.style.display = 'none';
    document.body.appendChild(element);

    element.click();

    document.body.removeChild(element);
  }

  onFileUpload(event: any) {
    const file: File = event.target.files[0];
    file.text().then(r => this.input = r.toString());
  }

  get output(): string {
    if (this.currentAlg == "HTML Encode") {
      let coder = new HtmlEncoder();
      return coder.encode(this.input);
    }
    else if (this.currentAlg == "HTML Decode") {
      let coder = new HtmlEncoder();
      return coder.decode(this.input);
    }
    else if (this.currentAlg == "Base32 Encode") {
      let coder = new Base32Encoder();
      return coder.encode(this.input);
    }
    else if (this.currentAlg == "Base32 Decode") {
      let coder = new Base32Encoder();
      return coder.decode(this.input);
    }
    else if (this.currentAlg == "Base64 Encode") {
      let coder = new Base64Encoder();
      return coder.encode(this.input);
    }
    else if (this.currentAlg == "Base64 Decode") {
      let coder = new Base64Encoder();
      return coder.decode(this.input);
    }
    else if (this.currentAlg == "URL Encode") {
      let coder = new UrlEncoder();
      return coder.encode(this.input);
    }
    else if (this.currentAlg == "URL Decode") {
      let coder = new UrlEncoder();
      return coder.decode(this.input);
    }
    else if (this.currentAlg == "Sort Lines") {
      let coder = new LineSorter();
      return coder.sort(this.input);
    }
    else if (this.currentAlg == "SHA512 Hash") {
      let coder = new SHA512Encoder();
      return coder.encode(this.input);
    }

    return "Unknown or unsuported selection: " + this.currentAlg;
  }

}

<div class="container">
  <div class="row">
    <div class="col">
      <h3>String Encode/Decode</h3>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <label>Action</label>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <select class="form-select" [(ngModel)]="currentAlg">

        <!--<optgroup label="Hash">-->
          <!--<option id="">SHA-1 Hash</option>-->
          <!--<option id="">SHA-2 Hash</option>-->
          <!--<option id="">SHA224 Hash</option>-->
          <!--<option id="">SHA256 Hash</option>-->
          <!--<option id="">SHA384 Hash</option>-->
          <!--<option id="">SHA512 Hash</option>-->
          <!--<option id="">SHA512/224</option>-->
          <!--<option id="">SHA512/256 Hash</option>-->
          <!--<option id="">SHA3-224 Hash</option>-->
          <!--<option id="">SHA3-256 Hash</option>-->
          <!--<option id="">SHA3-384 Hash</option>-->
          <!--<option id="">SHA3-512 Hash</option>-->
          <!--<option id="">CRC-16 Hash</option>-->
          <!--<option id="">CRC-32 Hash</option>-->
        <!--</optgroup>-->

        <optgroup label="HTML">
          <option id="html-encode">HTML Encode</option>
          <option id="html-decode">HTML Decode</option>
        </optgroup>

        <!--<optgroup label="Base32">
    <option id="base32-encode">Base32 Encode</option>
    <option id="base32-decode">Base32 Decode</option>
  </optgroup>-->

        <optgroup label="Base64">
          <option id="base64-encode">Base64 Encode</option>
          <option id="base64-decode">Base64 Decode</option>
        </optgroup>

        <optgroup label="URL">
          <option id="url-encode">URL Encode</option>
          <option id="url-decode">URL Decode</option>
        </optgroup>

        <optgroup label="Other">
          <option id="sort-lines">Sort Lines</option>
        </optgroup>

      </select>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <label>Input String</label>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <textarea class="form-control" rows="10" [(ngModel)]="input"></textarea>
    </div>
  </div>
  <div class="row">
    <div class="col">
    </div>
    <div class="col-auto text-right">
      <button class="btn btn-success ms-1 mt-1" type="button" (click)="selectFile.click()">Load File</button>
      <button class="btn btn-success ms-1 mt-1" type="button" (click)="onClear()">Clear</button>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <label>Output Code</label>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <textarea class="form-control" rows="10" readonly>{{output}}</textarea>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <button class="btn btn-success me-1 mt-1" (click)="onSave()">Save File</button>
    </div>
    <div class="col-auto text-right">
      <button class="btn btn-success ms-1 mt-1 float-right" type="button" (click)="onCopy()">Copy</button>
    </div>
  </div>
</div>

<input style="display: none" type="file" (change)="onFileUpload($event)" #selectFile>
