// src/pages/StringBuilder.tsx
import { useRef, useState } from 'react';

import { copyToClipboard, download, readUploadedFile } from '../lib/browser-io';

/** Turns pasted text into a C# string-concatenation literal. */
function buildOutput(content: string): string {
  let input = content;
  input = input.replace(/\r/g, '');
  input = input.replace(/"/g, '\\"');

  const lines = input.split('\n');
  if (lines.length === 0 || lines[0] === '') return '';

  let text = 'string text =';
  for (let i = 0; i < lines.length; i++) {
    text += `\r\n\t${i !== 0 ? '+' : ''}"${lines[i] === '\n' || lines[i] === '' ? '' : lines[i]}\\r\\n"`;
  }
  text += ';\r\n';

  return text;
}

export default function StringBuilder() {
  const [content, setContent] = useState('');
  const selectFile = useRef<HTMLInputElement>(null);

  const output = buildOutput(content);

  return (
    <>
      <div className="container">
        <div className="row">
          <div className="col">
            <h3>String Builder</h3>
          </div>
        </div>
        <div className="row">
          <div className="col">
            <label>Input String</label>
          </div>
        </div>
        <div className="row">
          <div className="col">
            <textarea
              className="form-control"
              rows={10}
              value={content}
              onChange={(e) => setContent(e.target.value)}
            />
          </div>
        </div>
        <div className="row">
          <div className="col"></div>
          <div className="col-auto text-right">
            <button
              className="btn btn-success ms-1 mt-1"
              type="button"
              onClick={() => selectFile.current?.click()}
            >
              Load File
            </button>
            <button className="btn btn-success ms-1 mt-1" type="button" onClick={() => setContent('')}>
              Clear
            </button>
          </div>
        </div>
        <div className="row">
          <div className="col">
            <label>Output Code</label>
          </div>
        </div>
        <div className="row">
          <div className="col">
            <textarea className="form-control" rows={10} readOnly value={output} />
          </div>
        </div>
        <div className="row">
          <div className="col">
            <button className="btn btn-success me-1 mt-1" onClick={() => download('code.cs', output)}>
              Save File
            </button>
          </div>
          <div className="col-auto text-right">
            <button
              className="btn btn-success ms-1 mt-1 float-right"
              type="button"
              onClick={() => copyToClipboard(output, 'Output copied to clipboard')}
            >
              Copy
            </button>
          </div>
        </div>
      </div>

      <input
        style={{ display: 'none' }}
        type="file"
        ref={selectFile}
        onChange={(e) => readUploadedFile(e, setContent)}
      />
    </>
  );
}

// src/app/pages/string-builder/string-builder.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-string-builder',
  templateUrl: './string-builder.component.html',
  styleUrls: ['./string-builder.component.css']
})
export class StringBuilderComponent implements OnInit {

  content: string = "";

  constructor() { }

  ngOnInit(): void {
  }

  onSave() {
    this.download("code.cs", this.output);
  }

  onClear() {
    this.content = "";
  }

  onCopy() {
    const el = document.createElement('textarea');
    el.value = this.output;
    el.setAttribute('readonly', '');
    el.style.position = 'absolute';
    el.style.left = '-9999px';
    document.body.appendChild(el);
    el.select();
    document.execCommand('copy');
    document.body.removeChild(el);

    alert("Output copied to clipboard");
  }

  download(filename: string, text: string) {
    let element = document.createElement('a');
    element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(text));
    element.setAttribute('download', filename);

    element.style.display = 'none';
    document.body.appendChild(element);

    element.click();

    document.body.removeChild(element);
  }

  onFileUpload(event: any) {
    const file: File = event.target.files[0];
    file.text().then(r => this.content = r.toString());
  }

  get output(): string {
    let input: string = this.content;
    input = input.replace(/\r/g, "");
    input = input.replace(/"/g, '\\"');

    let text = "string text =";
    let lines = input.split("\n");
    if (lines.length == 0 || lines[0] == "") return "";

    for (let i = 0; i < lines.length; i++) {
      text += `\r\n\t${i != 0 ? '+' : ''}"${lines[i] == "\n" || lines[i] == "" ? '' : lines[i]}\\r\\n"`;
    }
    text += ";\r\n";

    return text;
  }

}

<div class="container">
  <div class="row">
    <div class="col">
      <h3>String Builder</h3>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <label>Input String</label>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <textarea class="form-control" rows="10" [(ngModel)]="content"></textarea>
    </div>
  </div>
  <div class="row">
    <div class="col">
    </div>
    <div class="col-auto text-right">
      <button class="btn btn-success ms-1 mt-1" type="button" (click)="selectFile.click()">Load File</button>
      <button class="btn btn-success ms-1 mt-1" type="button" (click)="onClear()">Clear</button>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <label>Output Code</label>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <textarea class="form-control" rows="10" readonly>{{output}}</textarea>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <button class="btn btn-success me-1 mt-1" (click)="onSave()">Save File</button>
    </div>
    <div class="col-auto text-right">
      <button class="btn btn-success ms-1 mt-1 float-right" type="button" (click)="onCopy()">Copy</button>
    </div>
  </div>
</div>

<input style="display: none" type="file" (change)="onFileUpload($event)" #selectFile>
