// src/app/pages/guidgenerator/guidgenerator.component.ts
import { Component, OnInit } from '@angular/core';
import { v4 as uuidv4 } from 'uuid';

@Component({
  selector: 'app-guidgenerator',
  templateUrl: './guidgenerator.component.html',
  styleUrls: ['./guidgenerator.component.css']
})
export class GUIDGeneratorComponent implements OnInit {
  guids: string = "";

  constructor() { }

  ngOnInit(): void {
  }

  generateGuids() {
    this.guids = "";
    for (let i = 0; i < 10; i++) {
      let myuuid = uuidv4();
      this.guids += `${myuuid}\r\n`;
    }
  }

}

<div class="container">
  <div class="row">
    <div class="col">
      <h3>GUID Generator</h3>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <button type="button" class="btn btn-success mb-1" (click)="generateGuids()">Generate GUIDs</button>
    </div>
    <div class="row">
      <div class="col">
        <textarea class="form-control" rows="15">{{guids}}</textarea>
      </div>
    </div>
  </div>
</div>

// src/pages/GuidGenerator.tsx
import { useState } from 'react';
import { v4 as uuidv4 } from 'uuid';

export default function GuidGenerator() {
  const [guids, setGuids] = useState('');

  const generateGuids = () => {
    let next = '';
    for (let i = 0; i < 10; i++) {
      next += `${uuidv4()}\r\n`;
    }
    setGuids(next);
  };

  return (
    <div className="container">
      <div className="row">
        <div className="col">
          <h3>GUID Generator</h3>
        </div>
      </div>
      <div className="row">
        <div className="col">
          <button type="button" className="btn btn-success mb-1" onClick={generateGuids}>
            Generate GUIDs
          </button>
        </div>
        <div className="row">
          <div className="col">
            <textarea className="form-control" rows={15} readOnly value={guids} />
          </div>
        </div>
      </div>
    </div>
  );
}
