// src/pages/qrcodes/inputs/WiFiQrInput.tsx
import { useState } from 'react';

import QrInputCard from './QrInputCard';
import type { QrInputProps } from './types';
import './WiFiQrInput.css';

/*
    eg, 'WIFI:T:WPA;S:mynetwork;P:mypass;;'

      Parameter   Example    Description
      T           WPA        Authentication type; can be WEP or WPA or WPA2-EAP, or nopass for no password. Or, omit for no password.
      S           mynetwork  Network SSID. Required. Enclose in double quotes if it is an ASCII name, but could be interpreted as hex (i.e. "ABCD")
      P           mypass     Password, ignored if T is nopass (in which case it may be omitted). Enclose in double quotes if it is an ASCII name, but could be interpreted as hex (i.e. "ABCD")
      H           true       Optional. True if the network SSID is hidden. Note this was mistakenly also used to specify phase 2 method in releases up to 4.7.8 / Barcode Scanner 3.4.0. If not a boolean, it will be interpreted as phase 2 method (see below) for backwards-compatibility
      E           TTLS       (WPA2-EAP only) EAP method, like TTLS or PWD
      A           anon       (WPA2-EAP only) Anonymous identity
      I           myidentity (WPA2-EAP only) Identity
      PH2         MSCHAPV2   (WPA2-EAP only) Phase 2 method, like MSCHAPV2

    https://github.com/zxing/zxing/wiki/Barcode-Contents#wi-fi-network-config-android-ios-11
*/
export default function WiFiQrInput({ onGenerate }: QrInputProps) {
  const [T, setT] = useState('nopass');
  const [S, setS] = useState('');
  const [H, setH] = useState(false);
  const [P, setP] = useState('');

  const content = `WIFI:T:${T};S:${S};H:${H};P:${P};`;

  return (
    <QrInputCard title="Wi-Fi Connection" className="wifi-qr" onGenerate={() => onGenerate(content)}>
      <div className="row">
        <div className="col">
          <label>Authentication</label>
        </div>
      </div>

      <div className="row">
        <div className="col">
          <select className="form-select" value={T} onChange={(e) => setT(e.target.value)}>
            <option value="nopass">None</option>
            <option value="WEP">WEP</option>
            <option value="WPA">WPA / WPA2</option>
          </select>
        </div>
      </div>

      <div className="row">
        <div className="col">
          <label>Network Name</label>
        </div>
      </div>

      <div className="row">
        <div className="col">
          <input
            className="form-control"
            type="text"
            value={S}
            onChange={(e) => setS(e.target.value)}
          />
        </div>
      </div>

      <div className="row">
        <div className="col">
          <input
            type="checkbox"
            checked={H}
            onChange={(e) => setH(e.target.checked)}
            className="form-checkbox me-1"
          />
          <label>Hidden</label>
        </div>
      </div>

      <div className="row">
        <div className="col">
          <label>Password</label>
          <input
            className="form-control"
            type="password"
            value={P}
            onChange={(e) => setP(e.target.value)}
          />
        </div>
      </div>
    </QrInputCard>
  );
}

// src/app/pages/qrcodes/wi-fi-qr-input/wi-fi-qr-input.component.ts
import { Component, OnInit } from '@angular/core';
import { BaseQrInputComponent } from '../base-qr-input/base-qr-input.component';

@Component({
  selector: 'app-wi-fi-qr-input',
  templateUrl: './wi-fi-qr-input.component.html',
  styleUrls: ['./wi-fi-qr-input.component.css']
})
export class WiFiQrInputComponent extends BaseQrInputComponent {
  T: string = "nopass";
  S: string = "";
  H: boolean = false;
  P: string = "";

  private getRaw(): string {
    let raw: string = "WIFI:";
    raw += `T:${this.T};`;
    raw += `S:${this.S};`;
    raw += `H:${this.H};`;
    raw += `P:${this.P};`;
    return raw;
  }

  override get content(): string {
    return this.getRaw();
  }

  /*
      eg, 'WIFI:T:WPA;S:mynetwork;P:mypass;;'

        Parameter	  Example	  Description
        T	          WPA	      Authentication type; can be WEP or WPA or WPA2-EAP, or nopass for no password. Or, omit for no password.
        S	          mynetwork	  Network SSID. Required. Enclose in double quotes if it is an ASCII name, but could be interpreted as hex (i.e. "ABCD")
        P	          mypass	  Password, ignored if T is nopass (in which case it may be omitted). Enclose in double quotes if it is an ASCII name, but could be interpreted as hex (i.e. "ABCD")
        H	          true	      Optional. True if the network SSID is hidden. Note this was mistakenly also used to specify phase 2 method in releases up to 4.7.8 / Barcode Scanner 3.4.0. If not a boolean, it will be interpreted as phase 2 method (see below) for backwards-compatibility
        E	          TTLS	      (WPA2-EAP only) EAP method, like TTLS or PWD
        A	          anon	      (WPA2-EAP only) Anonymous identity
        I	          myidentity  (WPA2-EAP only) Identity
        PH2	          MSCHAPV2	  (WPA2-EAP only) Phase 2 method, like MSCHAPV2
*/
}
//https://github.com/zxing/zxing/wiki/Barcode-Contents#wi-fi-network-config-android-ios-11

<div class="card">
  <div class="card-header">Wi-Fi Connection</div>

  <div class="card-body">
    <div class="row">
      <div class="col">
        <label>Authentication</label>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <select class="form-select" [(ngModel)]="T">
          <option selected="selected" value="nopass">None</option>
          <option value="WEP">WEP</option>
          <option value="WPA">WPA / WPA2</option>
        </select>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <label>Network Name</label>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <input class="form-control" type="text" [(ngModel)]="S">
      </div>
    </div>

    <div class="row">
      <div class="col">
        <input type="checkbox" [(ngModel)]="H" class="form-checkbox me-1">
        <label>Hidden</label>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <label>Password</label>
        <input class="form-control" type="password" [(ngModel)]="P">
      </div>
    </div>

    <div class="row">
      <div class="col">
        <button type="button" class="mt-1 btn btn-success" (click)="onGenerateClick()">Generate</button>
      </div>
    </div>

  </div>
</div>
