// src/pages/StringLength.tsx
import { useRef, useState } from 'react';

import { copyToClipboard, download, readUploadedFile } from '../lib/browser-io';

export default function StringLength() {
  const [content, setContent] = useState('');
  const selectFile = useRef<HTMLInputElement>(null);

  const characterCount = content.length;
  const characterCountNoSpaces = content.replace(/\s/g, '').length;

  const wordCount = (() => {
    if (!content || content.trim() === '') {
      return 0;
    }

    // Split by whitespace and filter out empty strings
    return content.trim().split(/\s+/).filter((word) => word.length > 0).length;
  })();

  const lineCount = content ? content.split(/\r\n|\r|\n/).length : 0;

  return (
    <>
      <div className="container">
        <div className="row">
          <div className="col">
            <h3>Calculate String Length</h3>
          </div>
        </div>
        <div className="row">
          <div className="col">
            <label>Input String</label>
          </div>
        </div>
        <div className="row">
          <div className="col">
            <textarea
              className="form-control"
              rows={10}
              value={content}
              onChange={(e) => setContent(e.target.value)}
            />
          </div>
        </div>
        <div className="row">
          <div className="col">
            <button
              className="btn btn-success me-1 mt-1"
              onClick={() => download('content.txt', content)}
            >
              Save File
            </button>
          </div>
          <div className="col-auto text-right">
            <button
              className="btn btn-success ms-1 mt-1"
              type="button"
              onClick={() => selectFile.current?.click()}
            >
              Load File
            </button>
            <button className="btn btn-success ms-1 mt-1" type="button" onClick={() => setContent('')}>
              Clear
            </button>
            <button
              className="btn btn-success ms-1 mt-1 float-right"
              type="button"
              onClick={() => copyToClipboard(content, 'Contents copied to clipboard')}
            >
              Copy
            </button>
          </div>
        </div>

        {/* Statistics Section */}
        <div className="row mt-3">
          <div className="col">
            <div className="card">
              <div className="card-header">
                <h5 className="mb-0">Text Statistics</h5>
              </div>
              <div className="card-body">
                <div className="row">
                  <div className="col-md-3">
                    <div className="text-center">
                      <h6 className="text-muted">Characters</h6>
                      <h4 className="text-primary">{characterCount}</h4>
                    </div>
                  </div>
                  <div className="col-md-3">
                    <div className="text-center">
                      <h6 className="text-muted">Characters (no spaces)</h6>
                      <h4 className="text-primary">{characterCountNoSpaces}</h4>
                    </div>
                  </div>
                  <div className="col-md-3">
                    <div className="text-center">
                      <h6 className="text-muted">Words</h6>
                      <h4 className="text-success">{wordCount}</h4>
                    </div>
                  </div>
                  <div className="col-md-3">
                    <div className="text-center">
                      <h6 className="text-muted">Lines</h6>
                      <h4 className="text-info">{lineCount}</h4>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <input
        style={{ display: 'none' }}
        type="file"
        ref={selectFile}
        onChange={(e) => readUploadedFile(e, setContent)}
      />
    </>
  );
}

// src/app/pages/string-length/string-length.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-string-length',
  templateUrl: './string-length.component.html',
  styleUrls: ['./string-length.component.css']
})
export class StringLengthComponent implements OnInit {

  content: string = "";

  constructor() { }

  ngOnInit(): void {
  }

  onClear() {
    this.content = "";
  }

  onCopy() {
    const el = document.createElement('textarea');
    el.value = this.content;
    el.setAttribute('readonly', '');
    el.style.position = 'absolute';
    el.style.left = '-9999px';
    document.body.appendChild(el);
    el.select();
    document.execCommand('copy');
    document.body.removeChild(el);

    alert("Contents copied to clipboard");
  }

  onSave() {
    this.download("content.txt", this.content);
  }

  onFileUpload(event: any) {
    const file: File = event.target.files[0];
    file.text().then(r => this.content = r.toString());
  }

  download(filename: string, text: string) {
    let element = document.createElement('a');
    element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(text));
    element.setAttribute('download', filename);

    element.style.display = 'none';
    document.body.appendChild(element);

    element.click();

    document.body.removeChild(element);
  }

  get characterCount(): number {
    return this.content.length;
  }

  get wordCount(): number {
    if (!this.content || this.content.trim() === '') {
      return 0;
    }
    
    // Split by whitespace and filter out empty strings
    const words = this.content.trim().split(/\s+/).filter(word => word.length > 0);
    return words.length;
  }

  get lineCount(): number {
    if (!this.content) {
      return 0;
    }
    
    // Count lines by splitting on line breaks
    const lines = this.content.split(/\r\n|\r|\n/);
    return lines.length;
  }

  get characterCountNoSpaces(): number {
    return this.content.replace(/\s/g, '').length;
  }
}
<div class="container">
  <div class="row">
    <div class="col">
      <h3>Calculate String Length</h3>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <label>Input String</label>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <textarea class="form-control" rows="10" [(ngModel)]="content"></textarea>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <button class="btn btn-success me-1 mt-1" (click)="onSave()">Save File</button>
    </div>
    <div class="col-auto text-right">
      <button class="btn btn-success ms-1 mt-1" type="button" (click)="selectFile.click()">Load File</button>
      <button class="btn btn-success ms-1 mt-1" type="button" (click)="onClear()">Clear</button>
      <button class="btn btn-success ms-1 mt-1 float-right" type="button" (click)="onCopy()">Copy</button>
    </div>
  </div>
  
  <!-- Statistics Section -->
  <div class="row mt-3">
    <div class="col">
      <div class="card">
        <div class="card-header">
          <h5 class="mb-0">Text Statistics</h5>
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col-md-3">
              <div class="text-center">
                <h6 class="text-muted">Characters</h6>
                <h4 class="text-primary">{{characterCount}}</h4>
              </div>
            </div>
            <div class="col-md-3">
              <div class="text-center">
                <h6 class="text-muted">Characters (no spaces)</h6>
                <h4 class="text-primary">{{characterCountNoSpaces}}</h4>
              </div>
            </div>
            <div class="col-md-3">
              <div class="text-center">
                <h6 class="text-muted">Words</h6>
                <h4 class="text-success">{{wordCount}}</h4>
              </div>
            </div>
            <div class="col-md-3">
              <div class="text-center">
                <h6 class="text-muted">Lines</h6>
                <h4 class="text-info">{{lineCount}}</h4>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<input style="display: none" type="file" (change)="onFileUpload($event)" #selectFile>
