// src/app/pages/qrcodes/map-qr-input/map-qr-input.component.ts
import { Component, OnInit } from '@angular/core';
import { BaseQrInputComponent } from '../base-qr-input/base-qr-input.component';

@Component({
  selector: 'app-map-qr-input',
  templateUrl: './map-qr-input.component.html',
  styleUrls: ['./map-qr-input.component.css']
})
export class MapQrInputComponent extends BaseQrInputComponent {
  latitude: number = 0;
  latitudeSign: string = "N";
  longitude: number = 0;
  longitudeSign: string = "W";

  override get content(): string {
    return `geo:${this.latitudeSign == "S" ? "-" : ""}${this.latitude},${this.longitudeSign == "W" ? "-" : ""}${this.longitude},0`;
  }

}

<div class="container px-5 my-5">
  <div id="contactForm" data-sb-form-api-token="API_TOKEN">
    <div class="mb-3">
      <label class="form-label" for="latitude">Latitude</label>

      <div class="row">
        <div class="col-9">
          <input class="form-control" id="latitude" type="number" placeholder="Latitude" data-sb-validations="required" [(ngModel)]="latitude" />
        </div>
        <div class="col-3">
          <select class="form-select" id="latitudeSign" aria-label="LatitudeSign" [(ngModel)]="latitudeSign">
            <option value="N">N</option>
            <option value="S">S</option>
          </select>
        </div>
      </div>

    </div>

    <div class="mb-3">
      <label class="form-label" for="longitude">Longitude</label>

      <div class="row">
        <div class="col-9">
          <input class="form-control" id="longitude" type="text" placeholder="Longitude" data-sb-validations="required" [(ngModel)]="longitude" />
        </div>
        <div class="col-3">
          <select class="form-select" id="longitudeSign" aria-label="LongitudeSign" [(ngModel)]="longitudeSign">
            <option value="W">W</option>
            <option value="E">E</option>
          </select>
        </div>
      </div>

    </div>

    <div class="row">
      <div class="col">
        <button type="button" class="mt-1 btn btn-success" (click)="onGenerateClick()">Generate</button>
      </div>
    </div>

  </div>
</div>

// src/pages/qrcodes/inputs/MapQrInput.tsx
import { useState } from 'react';

import type { QrInputProps } from './types';

export default function MapQrInput({ onGenerate }: QrInputProps) {
  const [latitude, setLatitude] = useState('0');
  const [latitudeSign, setLatitudeSign] = useState('N');
  const [longitude, setLongitude] = useState('0');
  const [longitudeSign, setLongitudeSign] = useState('W');

  const content = `geo:${latitudeSign === 'S' ? '-' : ''}${latitude},${longitudeSign === 'W' ? '-' : ''}${longitude},0`;

  return (
    <div className="container px-5 my-5">
      <div id="contactForm">
        <div className="mb-3">
          <label className="form-label" htmlFor="latitude">Latitude</label>

          <div className="row">
            <div className="col-9">
              <input
                className="form-control"
                id="latitude"
                type="number"
                placeholder="Latitude"
                value={latitude}
                onChange={(e) => setLatitude(e.target.value)}
              />
            </div>
            <div className="col-3">
              <select
                className="form-select"
                id="latitudeSign"
                aria-label="LatitudeSign"
                value={latitudeSign}
                onChange={(e) => setLatitudeSign(e.target.value)}
              >
                <option value="N">N</option>
                <option value="S">S</option>
              </select>
            </div>
          </div>
        </div>

        <div className="mb-3">
          <label className="form-label" htmlFor="longitude">Longitude</label>

          <div className="row">
            <div className="col-9">
              <input
                className="form-control"
                id="longitude"
                type="text"
                placeholder="Longitude"
                value={longitude}
                onChange={(e) => setLongitude(e.target.value)}
              />
            </div>
            <div className="col-3">
              <select
                className="form-select"
                id="longitudeSign"
                aria-label="LongitudeSign"
                value={longitudeSign}
                onChange={(e) => setLongitudeSign(e.target.value)}
              >
                <option value="W">W</option>
                <option value="E">E</option>
              </select>
            </div>
          </div>
        </div>

        <div className="row">
          <div className="col">
            <button
              type="button"
              className="mt-1 btn btn-success"
              onClick={() => onGenerate(content)}
            >
              Generate
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
