// src/components/Toolbar.tsx
import { Link } from 'react-router';

export default function Toolbar() {
  return (
    <div className="container-fluid mb-3">
      <nav className="navbar navbar-expand-lg navbar-light bg-light">
        <div className="container-fluid">
          <Link className="navbar-brand" to="/">Developer Toolbox</Link>
          <button
            className="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span className="navbar-toggler-icon"></span>
          </button>
          <div className="collapse navbar-collapse" id="navbarSupportedContent">
            <ul className="navbar-nav me-auto mb-2 mb-lg-0">
              <li className="nav-item">
                <Link className="nav-link" to="/data-parser">Data Parser</Link>
              </li>
              {/* https://codebeautify.org/calculate-string-length */}
              <li className="nav-item">
                <Link className="nav-link" to="/string-length">String Length</Link>
              </li>
              <li className="nav-item">
                <Link className="nav-link" to="/string-builder">String Builder</Link>
              </li>
              <li className="nav-item">
                <Link className="nav-link" to="/string-encoder">String Encode/Decode</Link>
              </li>
              {/* http://asdfast.beobit.net/docs/ */}
              <li className="nav-item">
                <Link className="nav-link" to="/lorem-ipsum">Lorem Ipsum</Link>
              </li>
              {/* https://www.programmertools.online/generator/qrcode.html */}
              {/* https://www.npmjs.com/package/qrcode */}
              <li className="nav-item">
                <Link className="nav-link" to="/qr-codes">QR Codes</Link>
              </li>
              <li className="nav-item">
                <Link className="nav-link" to="/guid-generator">GUID Generator</Link>
              </li>
              <li className="nav-item">
                <Link className="nav-link" to="/relative-path">Relative Path</Link>
              </li>
              {/* see also:
                    https://www.browserling.com/tools
                    https://coding.tools
              */}
              {/* Bootstrap Forms (/bootstrap-forms) is routable but kept out of
                  the nav, same as in the Angular app. */}
            </ul>
          </div>
        </div>
      </nav>
    </div>
  );
}

// src/app/components/toolbar/toolbar.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  standalone: false,
  selector: 'app-toolbar',
  templateUrl: './toolbar.component.html',
  styleUrls: ['./toolbar.component.css']
})
export class ToolbarComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="container-fluid mb-3">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" routerLink="">Developer Toolbox</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" routerLink="data-parser">Data Parser</a>
          </li>
          <!--https://codebeautify.org/calculate-string-length-->
          <li class="nav-item">
            <a class="nav-link" routerLink="string-length">String Length</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" routerLink="string-builder">String Builder</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" routerLink="string-encoder">String Encode/Decode</a>
          </li>
          <!--http://asdfast.beobit.net/docs/-->
          <li class="nav-item">
            <a class="nav-link" routerLink="lorem-ipsum">Lorem Ipsum</a>
          </li>
          <!--https://www.programmertools.online/generator/qrcode.html-->
          <!--https://www.npmjs.com/package/qrcode-->
          <li class="nav-item">
            <a class="nav-link" routerLink="qr-codes">QR Codes</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" routerLink="guid-generator">GUID Generator</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" routerLink="relative-path">Relative Path</a>
          </li>
          <!--see also:
                  https://www.browserling.com/tools
                  https://coding.tools

          -->
          <!--<li class="nav-item">
            <a class="nav-link" routerLink="/bootstrap-forms">Bootstrap Forms</a>
          </li>-->
          <!--<li class="nav-item">
            <a class="nav-link" href="https://magicrings.org//PDF/Intro%20to%20Rings%20v1.6.pdf" target="_blank">Help</a>
          </li>-->
          <!--<li *ngIf="api.getCredentials().token == ''" class="nav-item">
            <a class="nav-link" href="login">Login/Register</a>
          </li>-->
        </ul>
        <!--<div *ngIf="api.getCredentials().token != ''" class="d-flex">
          <div class="">
            Hello, {{api.getCredentials().given_name}} {{api.getCredentials().family_name}}!
            <button type="button" class="btn btn-outline-success ms-2" (click)="logout()">Logout</button>
          </div>
        </div>-->
      </div>
    </div>
  </nav>
</div>
