// src/pages/qrcodes/QrCodes.tsx
import { useRef, useState } from 'react';
import QRCode from 'qrcode';

import ContactInfoQrInput from './inputs/ContactInfoQrInput';
import EmailQrInput from './inputs/EmailQrInput';
import MapQrInput from './inputs/MapQrInput';
import PhoneQrInput from './inputs/PhoneQrInput';
import SmsQrInput from './inputs/SmsQrInput';
import TextQrInput from './inputs/TextQrInput';
import UrlQrInput from './inputs/UrlQrInput';
import WiFiQrInput from './inputs/WiFiQrInput';
import './QrCodes.css';

// https://github.com/zxing/zxing/wiki/Barcode-Contents

export default function QrCodes() {
  const [type, setType] = useState('text');
  const canvas = useRef<HTMLCanvasElement>(null);

  const drawCanvas = (text: string) => {
    if (!canvas.current) {
      return;
    }

    QRCode.toCanvas(canvas.current, text, { width: 350 }, (error) => {
      if (error) console.error(error);
      console.log('success!');
    });
  };

  return (
    <div className="container qr-codes">
      <div className="row">
        <div className="col">
          <h1>QR Codes</h1>
          <div className="row">
            <div className="col">
              <label>Type</label>
              <select
                className="form-select mb-2"
                value={type}
                onChange={(e) => setType(e.target.value)}
              >
                <option value="text">Basic Text</option>
                <option value="url">URL Link</option>
                <option value="email">Email</option>
                <option value="phone">Phone Number</option>
                <option value="contactinfo">Contact Info</option>
                <option value="sms">SMS</option>
                <option value="map">Map</option>
                <option value="calendar">Calendar</option>
                <option value="wifi">WiFi Connection</option>
              </select>
            </div>
          </div>
          <div className="row">
            <div className="col mb-2">
              {type === 'text' && <TextQrInput onGenerate={drawCanvas} />}
              {type === 'url' && <UrlQrInput onGenerate={drawCanvas} />}
              {type === 'email' && <EmailQrInput onGenerate={drawCanvas} />}
              {type === 'phone' && <PhoneQrInput onGenerate={drawCanvas} />}
              {type === 'contactinfo' && <ContactInfoQrInput onGenerate={drawCanvas} />}
              {type === 'sms' && <SmsQrInput onGenerate={drawCanvas} />}
              {type === 'map' && <MapQrInput onGenerate={drawCanvas} />}
              {/* Calendar is still unfinished, so picking it renders nothing -
                  same as in the Angular app:
                  {type === 'calendar' && <CalendarQrInput onGenerate={drawCanvas} />} */}
              {type === 'wifi' && <WiFiQrInput onGenerate={drawCanvas} />}
            </div>
          </div>
        </div>
        <div className="col">
          <div className="row">
            <div className="col">
              <label>Image</label>
            </div>
          </div>
          <div className="row">
            <div className="col">
              <canvas id="canvas" ref={canvas}></canvas>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// src/app/pages/qrcodes/qrcodes.component.ts
import { Component, OnInit } from '@angular/core';
import * as QRCode from 'qrcode';

@Component({
  standalone: false,
  selector: 'app-qrcodes',
  templateUrl: './qrcodes.component.html',
  styleUrls: ['./qrcodes.component.css']
})
export class QRCodesComponent implements OnInit {

  type: string = "text";

  constructor() { }

  ngOnInit(): void {
  }

  drawCanvas(text: string) {
    const canvas = document.getElementById('canvas') as HTMLCanvasElement;

    QRCode.toCanvas(canvas, text, { width: 350 }, function (error: Error | null | undefined) {
      if (error) console.error(error);
      console.log('success!');
    });
  }
}

<!--<p>qrcodes works!</p>
<label>Content</label>
<textarea [(ngModel)]="content" rows="10"></textarea>
<br />
<button type="button" (click)="onGenerateClick()">Generate</button>
<br />
<canvas id="canvas"></canvas>-->
<!-- https://github.com/zxing/zxing/wiki/Barcode-Contents -->

<div class="container">
  <div class="row">
    <div class="col">
      <h1>QR Codes</h1>
      <div class="row">
        <div class="col>">
          <label>Type</label>
          <select class="form-select mb-2" [(ngModel)]="type">
            <option value="text">Basic Text</option>
            <option value="url">URL Link</option>
            <option value="email">Email</option>
            <option value="phone">Phone Number</option>
            <option value="contactinfo">Contact Info</option>
            <option value="sms">SMS</option>
            <option value="map">Map</option>
            <option value="calendar">Calendar</option>
            <option value="wifi">WiFi Connection</option>
          </select>
        </div>
      </div>
      <div class="row">
        <div class="col mb-2">
          <app-text-qr-input *ngIf="type=='text'" (contentEvent)="drawCanvas($event)"></app-text-qr-input>
          <app-url-qr-input *ngIf="type=='url'" (contentEvent)="drawCanvas($event)"></app-url-qr-input>
          <app-email-qr-input *ngIf="type=='email'" (contentEvent)="drawCanvas($event)"></app-email-qr-input>
          <app-phone-qr-input *ngIf="type=='phone'" (contentEvent)="drawCanvas($event)"></app-phone-qr-input>
          <app-contact-info-qr-input *ngIf="type=='contactinfo'" (contentEvent)="drawCanvas($event)"></app-contact-info-qr-input>
          <app-sms-qr-input *ngIf="type=='sms'" (contentEvent)="drawCanvas($event)"></app-sms-qr-input>
          <app-map-qr-input *ngIf="type=='map'" (contentEvent)="drawCanvas($event)"></app-map-qr-input>
          <!--<app-calendar-qr-input *ngIf="type=='calendar'" (contentEvent)="drawCanvas($event)"></app-calendar-qr-input>-->
          <app-wi-fi-qr-input *ngIf="type=='wifi'" (contentEvent)="drawCanvas($event)"></app-wi-fi-qr-input>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="row">
        <div class="col">
          <label>Image</label>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <canvas id="canvas"></canvas>
        </div>
      </div>     
    </div>
  </div>
</div>
