// src/pages/qrcodes/inputs/ContactInfoQrInput.tsx
import { useState } from 'react';

import QrInputCard from './QrInputCard';
import type { QrInputProps } from './types';
import './ContactInfoQrInput.css';

export default function ContactInfoQrInput({ onGenerate }: QrInputProps) {
  const [firstName, setFirstName] = useState('');
  const [lastName, setLastName] = useState('');
  const [phoneNumber, setPhoneNumber] = useState('');
  const [email, setEmail] = useState('');
  const [birthday, setBirthday] = useState('');
  const [address, setAddress] = useState('');
  const [website, setWebsite] = useState('');
  const [organization, setOrganization] = useState('');
  const [jobTitle, setJobTitle] = useState('');
  const [workPhoneNumber, setWorkPhoneNumber] = useState('');

  const buildVCard = (): string => {
    let value = '';

    value += 'BEGIN:VCARD\r\n';
    value += 'VERSION:4.0\r\n';
    value += `FN:${firstName} ${lastName}\r\n`;
    if (phoneNumber !== '') {
      value += `TEL;TYPE=cell:${phoneNumber}\r\n`;
    }
    if (email !== '') {
      value += `EMAIL:${email}\r\n`;
    }
    if (birthday !== '') {
      value += `BDAY:${birthday.replace('-', '').replace('-', '')}\r\n`;
    }
    if (address !== '') {
      //todo need to parse address
      //value += `ADR;TYPE=home:;;123 Main St.;Springfield;IL;12345;USA\r\n`;
      value += `ADR;TYPE=home:${address}\r\n`;
    }
    if (website !== '') {
      value += `URL:${website}\r\n`;
    }
    if (organization !== '') {
      value += `ORG:${organization}\r\n`;
    }
    if (jobTitle !== '') {
      value += `TITLE:${jobTitle}\r\n`;
    }
    if (workPhoneNumber !== '') {
      value += `TEL;TYPE=work:${workPhoneNumber}\r\n`;
    }

    value += 'END:VCARD';

    return value;
  };

  return (
    <QrInputCard
      title="Contact Information"
      className="contact-qr"
      onGenerate={() => onGenerate(buildVCard())}
    >
      <div className="row">
        <div className="col">
          <label>First Name</label>
        </div>
      </div>
      <div className="row">
        <div className="col">
          <input className="form-control" type="text" value={firstName} onChange={(e) => setFirstName(e.target.value)} />
        </div>
      </div>

      <div className="row">
        <div className="col">
          <label>Last Name</label>
        </div>
      </div>
      <div className="row">
        <div className="col">
          <input className="form-control" type="text" value={lastName} onChange={(e) => setLastName(e.target.value)} />
        </div>
      </div>

      <div className="row">
        <div className="col">
          <label>Phone Number</label>
        </div>
      </div>
      <div className="row">
        <div className="col">
          <input className="form-control" type="tel" value={phoneNumber} onChange={(e) => setPhoneNumber(e.target.value)} />
        </div>
      </div>

      <div className="row">
        <div className="col">
          <label>Email</label>
        </div>
      </div>
      <div className="row">
        <div className="col">
          <input className="form-control" type="email" value={email} onChange={(e) => setEmail(e.target.value)} />
        </div>
      </div>

      <div className="row">
        <div className="col">
          <label>Birthday</label>
        </div>
      </div>
      <div className="row">
        <div className="col">
          <input className="form-control" type="date" value={birthday} onChange={(e) => setBirthday(e.target.value)} />
          <button className="btn btn-success" type="button" onClick={() => setBirthday('')}>
            Clear
          </button>
        </div>
      </div>

      <div className="row">
        <div className="col">
          <label>Address</label>
        </div>
      </div>
      <div className="row">
        <div className="col">
          <input className="form-control" type="text" value={address} onChange={(e) => setAddress(e.target.value)} />
        </div>
      </div>

      <div className="row">
        <div className="col">
          <label>Website</label>
        </div>
      </div>
      <div className="row">
        <div className="col">
          <input className="form-control" type="text" value={website} onChange={(e) => setWebsite(e.target.value)} />
        </div>
      </div>

      <div className="row mt-3">
        <div className="col">
          <h5>Organization</h5>
        </div>
      </div>

      <div className="row">
        <div className="col">
          <label>Organization</label>
        </div>
      </div>
      <div className="row">
        <div className="col">
          <input className="form-control" type="text" value={organization} onChange={(e) => setOrganization(e.target.value)} />
        </div>
      </div>

      <div className="row">
        <div className="col">
          <label>Job Title</label>
        </div>
      </div>
      <div className="row">
        <div className="col">
          <input className="form-control" type="text" value={jobTitle} onChange={(e) => setJobTitle(e.target.value)} />
        </div>
      </div>

      <div className="row">
        <div className="col">
          <label>Phone Number Work</label>
        </div>
      </div>
      <div className="row">
        <div className="col">
          <input className="form-control" type="tel" value={workPhoneNumber} onChange={(e) => setWorkPhoneNumber(e.target.value)} />
        </div>
      </div>
    </QrInputCard>
  );
}

// src/app/pages/qrcodes/contact-info-qr-input/contact-info-qr-input.component.ts
import { Component, OnInit } from '@angular/core';
import { BaseQrInputComponent } from '../base-qr-input/base-qr-input.component';

@Component({
  selector: 'app-contact-info-qr-input',
  templateUrl: './contact-info-qr-input.component.html',
  styleUrls: ['./contact-info-qr-input.component.css']
})
export class ContactInfoQrInputComponent extends BaseQrInputComponent {
  prefix: string = "";
  firstName: string = "";
  lastName: string = "";
  phoneNumber: string = "";
  email: string = "";
  birthday: string = "";
  address: string = "";
  website: string = "";
  organization: string = "";
  jobTitle: string = "";
  workPhoneNumber: string = "";

  override get content(): string {
    let value: string = "";

    value += "BEGIN:VCARD\r\n";
    value += "VERSION:4.0\r\n";
    value += `FN:${this.firstName} ${this.lastName}\r\n`;
    if (this.phoneNumber != "") {
      value += `TEL;TYPE=cell:${this.phoneNumber}\r\n`;
    }
    if (this.email != "") {
      value += `EMAIL:${this.email}\r\n`;
    }
    if (this.birthday != "") {
      value += `BDAY:${this.birthday.replace("-","").replace("-","")}\r\n`;
    }
    if (this.address != "") {
      //todo need to parse address
      //value += `ADR;TYPE=home:;;123 Main St.;Springfield;IL;12345;USA\r\n`;
      value += `ADR;TYPE=home:${this.address}\r\n`;
    }
    if (this.website != "") {
      value += `URL:${this.website}\r\n`;
    }
    if (this.organization != "") {
      value += `ORG:${this.organization}\r\n`;
    }
    if (this.jobTitle != "") {
      value += `TITLE:${this.jobTitle}\r\n`;
    }
    if (this.workPhoneNumber != "") {
      value += `TEL;TYPE=work:${this.workPhoneNumber}\r\n`;
    }

    value += "END:VCARD";

    return value;
  }

  clearBirthday() {
    this.birthday = "";
  }
}

<div class="card">
  <div class="card-header">Contact Information</div>

  <div class="card-body">

    <!--<div class="row">
      <div class="col">
        <label>Prefix</label>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <input class="form-control" type="text" [(ngModel)]="prefix">
      </div>
    </div>-->

    <div class="row">
      <div class="col">
        <label>First Name</label>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <input class="form-control" type="text" [(ngModel)]="firstName">
      </div>
    </div>

    <div class="row">
      <div class="col">
        <label>Last Name</label>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <input class="form-control" type="text" [(ngModel)]="lastName">
      </div>
    </div>

    <div class="row">
      <div class="col">
        <label>Phone Number</label>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <input class="form-control" type="tel" [(ngModel)]="phoneNumber">
      </div>
    </div>

    <div class="row">
      <div class="col">
        <label>Email</label>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <input class="form-control" type="email" [(ngModel)]="email">
      </div>
    </div>

    <div class="row">
      <div class="col">
        <label>Birthday</label>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <input class="form-control" type="date" [(ngModel)]="birthday">
        <button class="btn btn-success" type="button" (click)="clearBirthday()">Clear</button>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <label>Address</label>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <input class="form-control" type="text" [(ngModel)]="address">
      </div>
    </div>

    <div class="row">
      <div class="col">
        <label>Website</label>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <input class="form-control" type="text" [(ngModel)]="website">
      </div>
    </div>

    <div class="row mt-3">
      <div class="col">
        <h5>
          Organization
        </h5>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <label>Organization</label>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <input class="form-control" type="text" [(ngModel)]="organization">
      </div>
    </div>

    <div class="row">
      <div class="col">
        <label>Job Title</label>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <input class="form-control" type="text" [(ngModel)]="jobTitle" />
      </div>
    </div>

    <div class="row">
      <div class="col">
        <label>Phone Number Work</label>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <input class="form-control" type="tel" [(ngModel)]="workPhoneNumber">
      </div>
    </div>

    <div class="row">
      <div class="col">
        <button type="button" class="mt-1 btn btn-success" (click)="onGenerateClick()">Generate</button>
      </div>
    </div>

  </div>

</div>
