// src/app/pages/data-parser/data-parser.component.ts
import { Component, OnInit } from '@angular/core';
import { Settings } from './settings-box/settings-box.component';

@Component({
  selector: 'data-parser',
  templateUrl: './data-parser.component.html',
  styleUrls: ['./data-parser.component.css']
})
export class DataParserComponent implements OnInit {

  settings: Settings = new Settings;
  inputText: string = '';

  constructor() { }

  ngOnInit(): void {
  }

  onInputTextChanged(newValue: any) {
    this.inputText = newValue;
  }

  onSettingsChanged(settings: Settings) {
    this.settings = settings;
  }
}

<div class="container-fluid">
  <div class="row">
    <div class="col-md-3">
      <app-settings-box (onSettingsChanged)="onSettingsChanged($event)"></app-settings-box>
    </div>
    <div class="col-md-9">
      <div class="row">
        <div class="col-md-12">
          <app-input-box (onInputTextChanged)="onInputTextChanged($event)"></app-input-box>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <app-output-box [inputText]="inputText" [settings]="settings"></app-output-box>
        </div>
      </div>
    </div>
  </div>
</div>

// src/pages/data-parser/DataParser.tsx
import { useState } from 'react';

import InputBox from './InputBox';
import OutputBox from './OutputBox';
import SettingsBox from './SettingsBox';
import { defaultSettings, type Settings } from './settings';
import './DataParser.css';

export default function DataParser() {
  const [settings, setSettings] = useState<Settings>(defaultSettings);
  const [inputText, setInputText] = useState('');

  return (
    <div className="container-fluid data-parser">
      <div className="row">
        <div className="col-md-3">
          <SettingsBox settings={settings} onSettingsChanged={setSettings} />
        </div>
        <div className="col-md-9">
          <div className="row">
            <div className="col-md-12">
              <InputBox inputText={inputText} onInputTextChanged={setInputText} />
            </div>
          </div>
          <div className="row">
            <div className="col-md-12">
              <OutputBox inputText={inputText} settings={settings} />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
