// src/app/pages/data-parser/settings-box/settings-box.component.ts
import { Component, OnInit } from '@angular/core';
import { Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-settings-box',
  templateUrl: './settings-box.component.html',
  styleUrls: ['./settings-box.component.css']
})
export class SettingsBoxComponent implements OnInit {

  settings: Settings = new Settings;
  @Output() onSettingsChanged = new EventEmitter<Settings>();

  constructor() { }

  ngOnInit(): void {
  }

  onDelimiterChange(entry: string) {
    this.settings.delimiter = entry;
    this.onSettingsChanged.emit(this.settings);
  }

  onDecimalSignChange(entry: string) {
    this.settings.decimalSign = entry;
    this.onSettingsChanged.emit(this.settings);
  }

  onTransformCaseChange(entry: string) {
    this.settings.transformCase = entry;
    this.onSettingsChanged.emit(this.settings);
  }

  onIndentWithChange(entry: string) {
    this.settings.indentWith = entry;
    this.onSettingsChanged.emit(this.settings);
  }

  onFirstRowHeaderChange() {
    this.onSettingsChanged.emit(this.settings);
  }

  onIncludeWhiteSpaceChange() {
    this.onSettingsChanged.emit(this.settings);
  }

}

export class Settings {
  delimiter: string = 'auto';
  decimalSign: string = 'dot';
  firstRowHeader: boolean = true;
  transformCase: string = 'none';
  includeWhiteSpace: boolean = true;
  indentWith: string = 'spaces';
}

<div class="container-fluid">

  <div class="row" id="description">
    <h1>Data Parser</h1>
    <p>Convert Excel data into one of several web-friendly formats, including HTML, JSON and XML.</p>
  </div>

  <hr />

  <!--https://stackoverflow.com/questions/43095710/how-correctly-bind-data-to-radio-buttons-in-angular2-->
  <div class="row" id="settings">
    <h3>Settings:</h3>
    <form>
      <div class="form-group mb-2">
        <label>Delimiter</label>
        <div>
          <div class="form-check form-check-inline">
            <input name="delimiter" id="delimiter_0" type="radio" class="form-check-input" value="delimiterAuto" [checked]="settings.delimiter === 'auto'" (change)="onDelimiterChange('auto')">
            <label for="delimiter_0" class="form-check-label">Auto</label>
          </div>
          <div class="form-check form-check-inline">
            <input name="delimiter" id="delimiter_1" type="radio" class="form-check-input" value="delimiterComma" [checked]="settings.delimiter === 'comma'" (change)="onDelimiterChange('comma')">
            <label for="delimiter_1" class="form-check-label">Comma</label>
          </div>
          <div class="form-check form-check-inline">
            <input name="delimiter" id="delimiter_2" type="radio" class="form-check-input" value="delimiterTab" [checked]="settings.delimiter === 'tab'" (change)="onDelimiterChange('tab')">
            <label for="delimiter_2" class="form-check-label">Tab</label>
          </div>
        </div>
      </div>
      <div class="form-group mb-2">
        <label>Decimal Sign</label>
        <div>
          <div class="form-check form-check-inline">
            <input name="decimal" id="decimal_0" type="radio" class="form-check-input" value="decimalDot" [checked]="settings.decimalSign === 'dot'" (change)="onDecimalSignChange('dot')">
            <label for="decimal_0" class="form-check-label">Dot</label>
          </div>
          <div class="form-check form-check-inline">
            <input name="decimal" id="decimal_1" type="radio" class="form-check-input" value="decimalComma" [checked]="settings.decimalSign === 'comma'" (change)="onDecimalSignChange('comma')">
            <label for="decimal_1" class="form-check-label">Comma</label>
          </div>
        </div>
      </div>
      <div class="form-group mb-2">
        <div>
          <div class="form-check form-check-inline">
            <input name="headersProvidedCB" id="headersProvidedCB_0" type="checkbox" class="form-check-input" value="true" [(ngModel)]="settings.firstRowHeader" (change)="onFirstRowHeaderChange()">
            <label for="headersProvidedCB_0" class="form-check-label">First row is the header</label>
          </div>
        </div>
      </div>
      <div class="form-group mb-2">
        <label>Transform</label>
        <div>
          <div class="form-check form-check-inline">
            <input name="headerModifications" id="headerModifications_0" type="radio" class="form-check-input" value="downcase" [checked]="settings.transformCase === 'downcase'" (change)="onTransformCaseChange('downcase')">
            <label for="headerModifications_0" class="form-check-label">Lowercase</label>
          </div>
          <div class="form-check form-check-inline">
            <input name="headerModifications" id="headerModifications_1" type="radio" class="form-check-input" value="upcase" [checked]="settings.transformCase === 'upcase'" (change)="onTransformCaseChange('upcase')">
            <label for="headerModifications_1" class="form-check-label">Uppercase</label>
          </div>
          <div class="form-check form-check-inline">
            <input name="headerModifications" id="headerModifications_2" type="radio" class="form-check-input" value="none" [checked]="settings.transformCase === 'none'" (change)="onTransformCaseChange('none')">
            <label for="headerModifications_2" class="form-check-label">None</label>
          </div>
        </div>
      </div>
      <div class="form-group mb-2">
        <div>
          <div class="form-check form-check-inline">
            <input name="includeWhiteSpaceCB" id="includeWhiteSpaceCB_0" type="checkbox" class="form-check-input" value="true" [(ngModel)]="settings.includeWhiteSpace" (change)="onIncludeWhiteSpaceChange()">
            <label for="includeWhiteSpaceCB_0" class="form-check-label">Include white space in output</label>
          </div>
        </div>
      </div>
      <div class="form-group mb-2">
        <label>Indent with</label>
        <div>
          <div class="form-check form-check-inline">
            <input name="indentType" id="indentType_0" type="radio" class="form-check-input" value="tabs" [checked]="settings.indentWith === 'tabs'" (change)="onIndentWithChange('tabs')">
            <label for="indentType_0" class="form-check-label">Tabs</label>
          </div>
          <div class="form-check form-check-inline">
            <input name="indentType" id="indentType_1" type="radio" class="form-check-input" value="spaces" [checked]="settings.indentWith === 'spaces'" (change)="onIndentWithChange('spaces')">
            <label for="indentType_1" class="form-check-label">Spaces</label>
          </div>
        </div>
      </div>
    </form>
  </div>

</div>

// src/pages/data-parser/SettingsBox.tsx
import type { Settings } from './settings';

interface SettingsBoxProps {
  settings: Settings;
  onSettingsChanged: (settings: Settings) => void;
}

export default function SettingsBox({ settings, onSettingsChanged }: SettingsBoxProps) {
  const update = (patch: Partial<Settings>) => onSettingsChanged({ ...settings, ...patch });

  return (
    <div className="container-fluid">
      <div className="row" id="description">
        <h1>Data Parser</h1>
        <p>Convert Excel data into one of several web-friendly formats, including HTML, JSON and XML.</p>
      </div>

      <hr />

      <div className="row" id="settings">
        <h3>Settings:</h3>
        <form>
          <div className="form-group mb-2">
            <label>Delimiter</label>
            <div>
              <div className="form-check form-check-inline">
                <input
                  name="delimiter"
                  id="delimiter_0"
                  type="radio"
                  className="form-check-input"
                  checked={settings.delimiter === 'auto'}
                  onChange={() => update({ delimiter: 'auto' })}
                />
                <label htmlFor="delimiter_0" className="form-check-label">Auto</label>
              </div>
              <div className="form-check form-check-inline">
                <input
                  name="delimiter"
                  id="delimiter_1"
                  type="radio"
                  className="form-check-input"
                  checked={settings.delimiter === 'comma'}
                  onChange={() => update({ delimiter: 'comma' })}
                />
                <label htmlFor="delimiter_1" className="form-check-label">Comma</label>
              </div>
              <div className="form-check form-check-inline">
                <input
                  name="delimiter"
                  id="delimiter_2"
                  type="radio"
                  className="form-check-input"
                  checked={settings.delimiter === 'tab'}
                  onChange={() => update({ delimiter: 'tab' })}
                />
                <label htmlFor="delimiter_2" className="form-check-label">Tab</label>
              </div>
            </div>
          </div>

          <div className="form-group mb-2">
            <label>Decimal Sign</label>
            <div>
              <div className="form-check form-check-inline">
                <input
                  name="decimal"
                  id="decimal_0"
                  type="radio"
                  className="form-check-input"
                  checked={settings.decimalSign === 'dot'}
                  onChange={() => update({ decimalSign: 'dot' })}
                />
                <label htmlFor="decimal_0" className="form-check-label">Dot</label>
              </div>
              <div className="form-check form-check-inline">
                <input
                  name="decimal"
                  id="decimal_1"
                  type="radio"
                  className="form-check-input"
                  checked={settings.decimalSign === 'comma'}
                  onChange={() => update({ decimalSign: 'comma' })}
                />
                <label htmlFor="decimal_1" className="form-check-label">Comma</label>
              </div>
            </div>
          </div>

          <div className="form-group mb-2">
            <div>
              <div className="form-check form-check-inline">
                <input
                  name="headersProvidedCB"
                  id="headersProvidedCB_0"
                  type="checkbox"
                  className="form-check-input"
                  checked={settings.firstRowHeader}
                  onChange={(e) => update({ firstRowHeader: e.target.checked })}
                />
                <label htmlFor="headersProvidedCB_0" className="form-check-label">
                  First row is the header
                </label>
              </div>
            </div>
          </div>

          <div className="form-group mb-2">
            <label>Transform</label>
            <div>
              <div className="form-check form-check-inline">
                <input
                  name="headerModifications"
                  id="headerModifications_0"
                  type="radio"
                  className="form-check-input"
                  checked={settings.transformCase === 'downcase'}
                  onChange={() => update({ transformCase: 'downcase' })}
                />
                <label htmlFor="headerModifications_0" className="form-check-label">Lowercase</label>
              </div>
              <div className="form-check form-check-inline">
                <input
                  name="headerModifications"
                  id="headerModifications_1"
                  type="radio"
                  className="form-check-input"
                  checked={settings.transformCase === 'upcase'}
                  onChange={() => update({ transformCase: 'upcase' })}
                />
                <label htmlFor="headerModifications_1" className="form-check-label">Uppercase</label>
              </div>
              <div className="form-check form-check-inline">
                <input
                  name="headerModifications"
                  id="headerModifications_2"
                  type="radio"
                  className="form-check-input"
                  checked={settings.transformCase === 'none'}
                  onChange={() => update({ transformCase: 'none' })}
                />
                <label htmlFor="headerModifications_2" className="form-check-label">None</label>
              </div>
            </div>
          </div>

          <div className="form-group mb-2">
            <div>
              <div className="form-check form-check-inline">
                <input
                  name="includeWhiteSpaceCB"
                  id="includeWhiteSpaceCB_0"
                  type="checkbox"
                  className="form-check-input"
                  checked={settings.includeWhiteSpace}
                  onChange={(e) => update({ includeWhiteSpace: e.target.checked })}
                />
                <label htmlFor="includeWhiteSpaceCB_0" className="form-check-label">
                  Include white space in output
                </label>
              </div>
            </div>
          </div>

          <div className="form-group mb-2">
            <label>Indent with</label>
            <div>
              <div className="form-check form-check-inline">
                <input
                  name="indentType"
                  id="indentType_0"
                  type="radio"
                  className="form-check-input"
                  checked={settings.indentWith === 'tabs'}
                  onChange={() => update({ indentWith: 'tabs' })}
                />
                <label htmlFor="indentType_0" className="form-check-label">Tabs</label>
              </div>
              <div className="form-check form-check-inline">
                <input
                  name="indentType"
                  id="indentType_1"
                  type="radio"
                  className="form-check-input"
                  checked={settings.indentWith === 'spaces'}
                  onChange={() => update({ indentWith: 'spaces' })}
                />
                <label htmlFor="indentType_1" className="form-check-label">Spaces</label>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  );
}
