// src/pages/RelativePath.tsx
import { useState } from 'react';

import { copyToClipboard } from '../lib/browser-io';
import './RelativePath.css';

function parsePath(path: string, delimiter: string): string[] {
  // Normalize the path and split by delimiter
  const normalized = path.replace(/^[A-Za-z]:/, '').replace(/^[/\\]+/, '').replace(/[/\\]+$/, '');
  return normalized
    .split(new RegExp(`[${delimiter === '/' ? '/' : '\\\\'}]+`))
    .filter((part) => part.length > 0);
}

function calcRelativePath(fromArray: string[], toArray: string[], splitBy: string): string {
  // Find the common prefix length
  let commonLength = 0;
  const minLength = Math.min(fromArray.length, toArray.length);

  for (let i = 0; i < minLength; i++) {
    if (fromArray[i] === toArray[i]) {
      commonLength++;
    } else {
      break;
    }
  }

  // Calculate how many levels to go up
  const upLevels = fromArray.length - commonLength;

  // Get the remaining path from target
  const remainingPath = toArray.slice(commonLength);

  // Build the relative path
  let result = '';

  // Add ".." for each level up
  for (let i = 0; i < upLevels; i++) {
    result += '..' + splitBy;
  }

  // Add the remaining path
  if (remainingPath.length > 0) {
    result += remainingPath.join(splitBy);
  }

  // Handle edge cases
  if (!result) {
    result = '.'; // Same directory
  } else if (result.endsWith(splitBy)) {
    result = result.slice(0, -1); // Remove trailing separator
  }

  return result;
}

export default function RelativePath() {
  const [firstPath, setFirstPath] = useState('');
  const [secondPath, setSecondPath] = useState('');
  const [result1, setResult1] = useState('');
  const [result2, setResult2] = useState('');
  const [showResults, setShowResults] = useState(false);

  const calculate = () => {
    if (!firstPath || !secondPath) {
      return;
    }

    // Detect path separator
    const isUnix = firstPath.indexOf('/') > -1;
    const splitBy = isUnix ? '/' : '\\';

    // Parse paths
    const firstArray = parsePath(firstPath, splitBy);
    const secondArray = parsePath(secondPath, splitBy);

    // Calculate both relative paths
    setResult1(calcRelativePath(firstArray, secondArray, splitBy));
    setResult2(calcRelativePath(secondArray, firstArray, splitBy));
    setShowResults(true);
  };

  const reset = () => {
    setFirstPath('');
    setSecondPath('');
    setResult1('');
    setResult2('');
    setShowResults(false);
  };

  const onEnter = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Enter') {
      calculate();
    }
  };

  return (
    <div className="container relative-path">
      <div className="row">
        <div className="col">
          <h1>Relative Path Calculator</h1>
          <p>Calculate the relative path between two file or directory paths.</p>
        </div>
      </div>

      <div className="row mt-3">
        <div className="col-md-6">
          <div className="card">
            <div className="card-header">From Path</div>
            <div className="card-body">
              <input
                type="text"
                className="form-control"
                value={firstPath}
                onChange={(e) => setFirstPath(e.target.value)}
                placeholder="e.g., C:\Users\Documents\project or /home/user/project"
                onKeyDown={onEnter}
              />
              <small className="form-text text-muted mt-2">
                Enter the source path (supports both Windows and Unix paths)
              </small>
            </div>
          </div>
        </div>

        <div className="col-md-6">
          <div className="card">
            <div className="card-header">To Path</div>
            <div className="card-body">
              <input
                type="text"
                className="form-control"
                value={secondPath}
                onChange={(e) => setSecondPath(e.target.value)}
                placeholder="e.g., C:\Users\Pictures\vacation or /home/user/photos"
                onKeyDown={onEnter}
              />
              <small className="form-text text-muted mt-2">Enter the destination path</small>
            </div>
          </div>
        </div>
      </div>

      <div className="row mt-3">
        <div className="col text-center">
          <button
            className="btn btn-success btn-lg me-2"
            onClick={calculate}
            disabled={!firstPath || !secondPath}
          >
            Calculate
          </button>
          <button className="btn btn-secondary btn-lg" onClick={reset}>
            Reset
          </button>
        </div>
      </div>

      {showResults && (
        <div className="row mt-4">
          <div className="col-md-6">
            <div className="card border-success">
              <div className="card-header bg-success text-white">Result: From Path → To Path</div>
              <div className="card-body">
                <div className="d-flex justify-content-between align-items-center">
                  <code className="flex-grow-1">{result1}</code>
                  <button
                    className="btn btn-sm btn-outline-primary ms-2"
                    onClick={() => copyToClipboard(result1, 'Copied to clipboard!')}
                  >
                    Copy
                  </button>
                </div>
              </div>
            </div>
          </div>

          <div className="col-md-6">
            <div className="card border-info">
              <div className="card-header bg-info text-white">Result: To Path → From Path</div>
              <div className="card-body">
                <div className="d-flex justify-content-between align-items-center">
                  <code className="flex-grow-1">{result2}</code>
                  <button
                    className="btn btn-sm btn-outline-primary ms-2"
                    onClick={() => copyToClipboard(result2, 'Copied to clipboard!')}
                  >
                    Copy
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

// src/app/pages/relative-path/relative-path.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-relative-path',
  templateUrl: './relative-path.component.html',
  styleUrls: ['./relative-path.component.css']
})
export class RelativePathComponent implements OnInit {
  firstPath: string = '';
  secondPath: string = '';
  result1: string = '';
  result2: string = '';
  showResults: boolean = false;

  constructor() { }

  ngOnInit(): void {
  }

  calculate(): void {
    if (!this.firstPath || !this.secondPath) {
      return;
    }

    // Detect path separator
    const isUnix = this.firstPath.indexOf('/') > -1;
    const splitBy = isUnix ? '/' : '\\';

    // Parse paths
    const firstArray = this.parsePath(this.firstPath, splitBy);
    const secondArray = this.parsePath(this.secondPath, splitBy);

    // Calculate both relative paths
    this.result1 = this.calcRelativePath(firstArray, secondArray, splitBy);
    this.result2 = this.calcRelativePath(secondArray, firstArray, splitBy);
    this.showResults = true;
  }

  private parsePath(path: string, delimiter: string): string[] {
    // Normalize the path and split by delimiter
    const normalized = path.replace(/^[A-Za-z]:/, '').replace(/^[\/\\]+/, '').replace(/[\/\\]+$/, '');
    return normalized.split(new RegExp(`[${delimiter === '/' ? '/' : '\\\\'}]+`)).filter(part => part.length > 0);
  }

  private calcRelativePath(fromArray: string[], toArray: string[], splitBy: string): string {
    // Find the common prefix length
    let commonLength = 0;
    const minLength = Math.min(fromArray.length, toArray.length);
    
    for (let i = 0; i < minLength; i++) {
      if (fromArray[i] === toArray[i]) {
        commonLength++;
      } else {
        break;
      }
    }

    // Calculate how many levels to go up
    const upLevels = fromArray.length - commonLength;
    
    // Get the remaining path from target
    const remainingPath = toArray.slice(commonLength);

    // Build the relative path
    let result = '';
    
    // Add ".." for each level up
    for (let i = 0; i < upLevels; i++) {
      result += '..' + splitBy;
    }
    
    // Add the remaining path
    if (remainingPath.length > 0) {
      result += remainingPath.join(splitBy);
    }

    // Handle edge cases
    if (!result) {
      result = '.'; // Same directory
    } else if (result.endsWith(splitBy)) {
      result = result.slice(0, -1); // Remove trailing separator
    }

    return result;
  }

  reset(): void {
    this.firstPath = '';
    this.secondPath = '';
    this.result1 = '';
    this.result2 = '';
    this.showResults = false;
  }

  copyToClipboard(text: string): void {
    const el = document.createElement('textarea');
    el.value = text;
    el.setAttribute('readonly', '');
    el.style.position = 'absolute';
    el.style.left = '-9999px';
    document.body.appendChild(el);
    el.select();
    document.execCommand('copy');
    document.body.removeChild(el);
    alert('Copied to clipboard!');
  }
}

<div class="container">
  <div class="row">
    <div class="col">
      <h1>Relative Path Calculator</h1>
      <p>Calculate the relative path between two file or directory paths.</p>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col-md-6">
      <div class="card">
        <div class="card-header">From Path</div>
        <div class="card-body">
          <input 
            type="text" 
            class="form-control" 
            [(ngModel)]="firstPath" 
            placeholder="e.g., C:\Users\Documents\project or /home/user/project"
            (keyup.enter)="calculate()">
          <small class="form-text text-muted mt-2">
            Enter the source path (supports both Windows and Unix paths)
          </small>
        </div>
      </div>
    </div>

    <div class="col-md-6">
      <div class="card">
        <div class="card-header">To Path</div>
        <div class="card-body">
          <input 
            type="text" 
            class="form-control" 
            [(ngModel)]="secondPath" 
            placeholder="e.g., C:\Users\Pictures\vacation or /home/user/photos"
            (keyup.enter)="calculate()">
          <small class="form-text text-muted mt-2">
            Enter the destination path
          </small>
        </div>
      </div>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col text-center">
      <button class="btn btn-success btn-lg me-2" (click)="calculate()" [disabled]="!firstPath || !secondPath">
        Calculate
      </button>
      <button class="btn btn-secondary btn-lg" (click)="reset()">
        Reset
      </button>
    </div>
  </div>

  <div class="row mt-4" *ngIf="showResults">
    <div class="col-md-6">
      <div class="card border-success">
        <div class="card-header bg-success text-white">
          Result: From Path → To Path
        </div>
        <div class="card-body">
          <div class="d-flex justify-content-between align-items-center">
            <code class="flex-grow-1">{{result1}}</code>
            <button class="btn btn-sm btn-outline-primary ms-2" (click)="copyToClipboard(result1)">
              Copy
            </button>
          </div>
        </div>
      </div>
    </div>

    <div class="col-md-6">
      <div class="card border-info">
        <div class="card-header bg-info text-white">
          Result: To Path → From Path
        </div>
        <div class="card-body">
          <div class="d-flex justify-content-between align-items-center">
            <code class="flex-grow-1">{{result2}}</code>
            <button class="btn btn-sm btn-outline-primary ms-2" (click)="copyToClipboard(result2)">
              Copy
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>

<!--
  <div class="row mt-4">
    <div class="col">
      <div class="card">
        <div class="card-header">Examples</div>
        <div class="card-body">
          <h6>Windows Paths:</h6>
          <ul>
            <li>From: <code>C:\Users\Documents\project</code></li>
            <li>To: <code>C:\Users\Pictures\vacation</code></li>
            <li>Result: <code>..\..\Pictures\vacation</code></li>
          </ul>
          <h6 class="mt-3">Unix Paths:</h6>
          <ul>
            <li>From: <code>/home/user/project/src</code></li>
            <li>To: <code>/home/user/data/files</code></li>
            <li>Result: <code>../../data/files</code></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
    -->
</div>
